In [11]:
#import numpy # numpy.methode
import numpy as np # np.methode

my_array = np.array([1, 2, 3])

print(my_array)
print(my_array.shape)

[1 2 3]
(3,)


In [18]:
my_array2 = np.array([1, 0, 0, 1])

print(my_array2)
print(my_array2.shape)

my_array3 = my_array2.reshape((2, 2))

print(my_array3)
print(my_array3.shape)

[1 0 0 1]
(4,)
[[1 0]
 [0 1]]
(2, 2)


In [41]:
my_zero = np.zeros(shape=(3, 3), dtype=np.float32)

print(my_zero)

my_zero.astype(np.int8, copy=False)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [44]:
np.linalg.eig(my_array3)

(array([1., 1.]), array([[1., 0.],
        [0., 1.]]))